# Generated by Django 4.1.7 on 2023-03-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
