# Generated by Django 4.1.7 on 2023-03-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='option_A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='option_B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='option_C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d',
            new_name='option_D',
        ),
    ]
