# Generated by Django 4.1.7 on 2023-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_title_quiz_name_alter_quiz_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='subjects',
            field=models.ManyToManyField(to='quiz.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(to='quiz.topic'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
