# Generated by Django 4.1.7 on 2023-04-04 20:37

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_subject_remove_quiz_topic_quiz_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.topic'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
