# Generated by Django 4.1.7 on 2023-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_topic_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('questions', models.ManyToManyField(to='quiz.question')),
                ('subject', models.ManyToManyField(blank=True, null=True, to='quiz.subject')),
                ('topics', models.ManyToManyField(null=True, to='quiz.topic')),
            ],
        ),
    ]
